# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0004_authtoken_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='expires',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
