# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0004_authtoken_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='encrypted',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
