# Generated by Django 2.2.5 on 2019-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='auto_refresh',
            field=models.NullBooleanField(),
        ),
    ]
