# Generated by Django 3.1.6 on 2021-02-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='token_key',
        ),
    ]
