# Generated by Django 4.2.13 on 2024-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0009_extend_authtoken_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
