# Generated by Django 5.0.7 on 2024-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0009_extend_authtoken_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token_key',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
