# Generated by Django 5.0.7 on 2024-08-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knox", "0009_extend_authtoken_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authtoken",
            name="token_key",
        ),
    ]
