repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.31.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0b1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
